version: "3.9"
services:
  api:
    build: .
    command: api.py
    ports:
      - "8080:8080"
    links:
      - mqtt
    volumes:
      - "~/.aws:/root/.aws"

  register-measurement:
    build: .
    command: register_measurement.py
    links:
      - mqtt
    volumes:
      - "~/.aws:/root/.aws"

  agent:
    build: .
    command: agent.py
    links:
      - mqtt
    volumes:
      - "~/.aws:/root/.aws"

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
